version: '3'
services:
  fsenketo:
    image: qlands/fsenketo:3.0.1
    container_name: climmobEnketo
    networks:
      fsenketo:
        ipv4_address: 192.164.1.1
    environment:
      ENKETO_SRC_DIR: /srv/src/enketo_express
      WAIT_HOSTS: 192.164.1.2:6379, 192.164.1.3:6379
    volumes:
      - /opt/enketo/secrets:/srv/src/enketo_express/setup/docker/secrets
      - /opt/enketo/config:/srv/src/enketo_express/config
    ports:
      - 8005:8005
  fsredis:
    image: redis:5
    container_name: climmobRedis_main
    networks:
      fsenketo:
        ipv4_address: 192.164.1.2
    volumes:
      - /opt/enketo/redis:/data/
  fsredis2:
    image: redis:5
    container_name: climmobRedis_cache
    networks:
      fsenketo:
        ipv4_address: 192.164.1.3
    volumes:
      - /opt/enketo/redis_cache:/data/
networks:
  fsenketo:
     ipam:
        driver: default
        config:
          - subnet: 192.164.1.0/16
